mainapp/datas/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class NewDataForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])

    submit = SubmitField('Add')

mainapp/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class NewForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    form = TextAreaField('Form', validators=[DataRequired()])

    submit = SubmitField('Create')


class EditForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    form = TextAreaField('Form', validators=[DataRequired()])

    submit = SubmitField('Update')

mainapp/forms/routes.py
import copy
import json


from flask import Blueprint, request, abort, jsonify
from flask_login import login_required,current_user
from mainapp.forms.forms import NewForm, EditForm
from mainapp.forms.utils import create_form_class, combine_data, return_json, check_type_json, return_data
from mainapp import db


from flask import render_template, url_for, flash, redirect

from mainapp.models import Forms, Formsdata

forms = Blueprint('forms', __name__)



@forms.route("/forms", methods=['GET', 'POST'])
def form():
    data = Forms.query.all()
    return return_data(data, request.args.get('type'),
                       render_template('forms.html', title='Forms', data=data))


@forms.route("/newform", methods=['GET', 'POST'])
@login_required
def new_form():
    if check_type_json(request.args.get('type')):
        if request.method == 'GET':
            return jsonify({'message': 'Use POST method!'}), 400

        if request.content_type != 'application/json':
            return jsonify({'message': 'Content-Type must be application/json'}), 415

        try:
            json_data = request.get_json()
            if not json_data or not 'title' in json_data or not 'description' in json_data:
                return jsonify({'message': 'Invalid input'}), 400

            collections = Forms(title=json_data.get('title'), description=json_data.get('description'), form=json_data.get('form'),
                                author=current_user)
            db.session.add(collections)
            db.session.commit()
            return jsonify({'message': 'Add new form'}), 201

        except Exception as e:
            return jsonify({'message': 'Invalid JSON', 'error': str(e)}), 400


    form = NewForm()
    if form.validate_on_submit():
        collections = Forms(title=form.title.data, description=form.description.data, form=form.form.data, author=current_user)
        db.session.add(collections)
        db.session.commit()

        flash('Form created!', 'success')
        return redirect(url_for('forms.form'))
    elif request.method == 'GET':
        form.form.data = '''
        {
            "fields": [
                {"name": "title", "type": "StringField", "label": "Title", "validators": ["DataRequired"]},
                {"name": "content", "type": "TextAreaField", "label": "Content", "validators": ["DataRequired"]},
                {"name": "x", "type": "TextAreaField", "label": "X", "validators": ["DataRequired"]},
                {"name": "y", "type": "TextAreaField", "label": "Y", "validators": ["DataRequired"]},
                {"name": "radio_element", "type": "RadioField", "label": "Radio Field", "validators": ["DataRequired"],
                  "choices": [["M","Male"],["F","Female"]]},
                {"name": "boool_field", "type": "BooleanField", "label": "Remember me",  "validators": []} 
            ],
            "submit": {"label": "Add"}
        }
        '''

    return render_template('new_form.html', title='Form',legend='New Form', form=form)




@forms.route("/forms/<id>", methods=['GET', 'POST'])
def form_view(id):
    count = Formsdata.query.filter_by(form_id=id).count()
    form = Forms.query.with_entities(Forms.title, Forms.description).filter_by(id=id).first()

    if check_type_json(request.args.get('type')):
        return jsonify({'count': count, 'form': {'title': form.title,
                                                 'description': form.description
        }})
    return render_template('form_root.html', title='Form', form=form, id=id, count=count)


@forms.route("/forms/<id>/new", methods=['GET', 'POST'])
@login_required
def form_add(id):
    if check_type_json(request.args.get('type')):
        if request.method == 'GET':
            return jsonify({'message': 'Use POST method!'}), 400

        if request.content_type != 'application/json':
            return jsonify({'message': 'Content-Type must be application/json'}), 415

        try:
            json_data = request.get_json()
            if not json_data or not 'data' in json_data:
                return jsonify({'message': 'Invalid input'}), 400

            formdata = Formsdata(data=json.dumps(json_data.get('data')), form_id=id, author=current_user)
            db.session.add(formdata)
            db.session.commit()

            return jsonify({'message': f'Add new row in form: {id}'}), 201

        except Exception as e:
            return jsonify({'message': 'Invalid JSON', 'error': str(e)}), 400


    data = Forms.query.filter_by(id=id).first_or_404()
    form_definition = json.loads(data.form.replace("'", '"'))
    dynamicForm = create_form_class(form_definition)
    form = dynamicForm()

    if form.validate_on_submit():
        form_data = {field.name: field.data for field in form if field.name not in ('csrf_token', 'submit') }
        form_data_json = json.dumps(form_data)
        formdata = Formsdata(data=form_data_json, form_id=id, author=current_user)
        db.session.add(formdata)
        db.session.commit()

        flash('Data add to db!', 'success')
        return redirect(url_for('forms.form_view', id=id))
    return render_template('form.html', title=data.title, description=data.description, form=form, form_config=form_definition)

@forms.route("/forms/<id>/edit", methods=['GET', 'POST'])
@login_required
def form_edit(id):
    data = Forms.query.filter_by(id=id).first_or_404()

    if data.author != current_user:
        abort(403)

    form = EditForm()
    if form.validate_on_submit():
        data.title = form.title.data
        data.description = form.description.data
        data.form = form.form.data
        db.session.commit()
        flash('Form updated!', 'success')
        return redirect(url_for('forms.form_view', id=id))

    elif request.method == 'GET':

        form.title.data =  data.title
        form.description.data = data.description
        form.form.data = data.form

    return render_template('new_form.html', title='Form', legend='Edit Form', form=form)
@forms.route("/forms/<id>/delete", methods=['GET', 'POST'])
@login_required
def form_delete(id):
    data = Forms.query.filter_by(id=id).first_or_404()

    if data.author != current_user:
        abort(403)
    db.session.delete(data)
    Formsdata.query.filter_by(form_id=id).delete()
    db.session.commit()
    flash(f'Form has been deleted! [{id}]', 'success')
    return redirect(url_for('forms.form'))

@forms.route("/forms/<id>/table", methods=['GET', 'POST'])
def form_table(id):
    form = Forms.query.filter_by(id=id).first()
    form_data = json.loads(form.form.replace("'", '"'))
    data = Formsdata.query.filter_by(form_id=id).all()

    d = []
    for x in data:

        d.append([{"id": x.id}] + combine_data(x.data, form_data['fields']))

    if check_type_json(request.args.get('type')):
        return jsonify({'form': d })
    return render_template('formview.html', title='Form', form=d, id=id)


@forms.route("/forms/<id>/table/<objectid>", methods=['GET', 'POST'])
def form_single_item(id, objectid):
    form = Forms.query.filter_by(id=id).first()
    form_data = json.loads(form.form.replace("'", '"'))
    data = Formsdata.query.filter_by(form_id=id, id=objectid).all()

    d = []
    for x in data:
        d.append(combine_data(x.data, form_data['fields']))

    if check_type_json(request.args.get('type')):
        return jsonify({'form': d })
    return render_template('formsinglerecord.html', title='Form', form=d, id=id, objectid=objectid, meta=data)

@forms.route("/forms/<id>/table/<objectid>/edit", methods=['GET', 'POST'])
def form_single_item_edit(id, objectid):
    data = Forms.query.filter_by(id=id).first_or_404()
    form_definition = json.loads(data.form.replace("'", '"'))
    dynamicForm = create_form_class(form_definition)
    form = dynamicForm()

    form_data = Formsdata.query.filter_by(form_id=id, id=objectid).first()

    if form.validate_on_submit():
        tech_field = ('csrf_token', 'submit')
        for field in form:
            if field.name not in tech_field:
                setattr(form_data, field.name, field.data)

        form_data_json = json.dumps(
            {field.name: field.data for field in form if field.name not in tech_field})
        form_data.data = form_data_json

        db.session.commit()

        flash('Data update in db!', 'success')
        return redirect(url_for('forms.form_view', id=id))

    elif request.method == 'GET':

        for f in form_definition['fields']:
            field_name = f['name']
            field_data = json.loads(form_data.data)
            form[field_name].data = field_data.get(field_name)

    if check_type_json(request.args.get('type')):
        return jsonify({'info': "TODO"})

    return render_template('formsinglerecordedit.html', title='Form', form=form, form_config=form_definition, id=id, objectid=objectid, meta=data)

mainapp/datas/routes.py
from flask import render_template, url_for, flash, redirect, request, abort
from mainapp import db
from mainapp.models import  Collection
from mainapp.datas.forms import NewDataForm
from flask_login import current_user, login_required


from flask import Blueprint

datas = Blueprint('datas', __name__)

@datas.route("/data")
def dataall():
    page = request.args.get('page', 1, type=int)
    data = Collection.query.order_by(Collection.date_created.desc()).paginate(page=page, per_page=5)

    #data = Collection.query.paginate(page=page, per_page=5)
    return render_template('datas.html', posts=data)




@datas.route("/data/new", methods=['GET', 'POST'])
@login_required
def new_data():
    form = NewDataForm()
    if form.validate_on_submit():
        collections = Collection(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(collections)
        db.session.commit()

        flash('Add data', 'success')
        return redirect(url_for('data.new'))


    return render_template('create_data.html', title="New data", form=form, legend="New data")


@datas.route("/data/<data_id>")
def data(data_id):
    data = Collection.query.get_or_404(data_id)
    return render_template('data.html', title=data.title, data=data)


@datas.route("/data/<data_id>/update", methods=['GET', 'POST'])
@login_required
def updatedata(data_id):
    data = Collection.query.get_or_404(data_id)
    if(data.author != current_user):
        abort(403)
    form = NewDataForm()
    if form.validate_on_submit():
        data.title = form.title.data
        data.content = form.content.data
        db.session.commit()
        flash('Data updated!', 'success')
        return redirect(url_for('datas.data', data_id=data.id))

    elif request.method == 'GET':

        form.title.data =  data.title
        form.content.data = data.content
    return render_template('create_data.html', title="Update data", form=form, legend="Update data")


@datas.route("/data/<data_id>/delete", methods=['GET', 'POST'])
@login_required
def deletedata(data_id):
    data = Collection.query.get_or_404(data_id)
    if(data.author != current_user):
        abort(403)
    db.session.delete(data)
    db.session.commit()
    flash('Data has been deleted!', 'success')
    return redirect(url_for('.main.home'))

mainapp/users/routes.py
from flask import Blueprint, jsonify

import bcrypt
from flask import render_template, url_for, flash, redirect, request, abort
from mainapp import db, bcrypt
from mainapp.forms.utils import check_type_json
from mainapp.models import User, Collection
from mainapp.users.forms import (RegistrationForm,
                           LoginForm,
                           UpdateAccountForm,
                           RequestResetForm,
                           ResetPasswordForm)
from flask_login import login_user, current_user, logout_user, login_required

from mainapp.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if check_type_json(request.args.get('type')):
        print()

        data = request.get_json()
        username = data.get('username')
        password = data.get('password')
        remember = data.get('remember')
        user = User.query.filter_by(username=username).first()

        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user, remember=remember)
            return jsonify({'message': 'Logged in successfully'}), 200
        return jsonify({'message': 'Invalid credentials'}), 401



    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check emil and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account",  methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('You account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_foto/' + current_user.image_file)
    return render_template(
        'account.html', title='Account', image_file=image_file, form=form)

@users.route("/user/<string:username>")
def userdata(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    data = Collection.query.filter_by(author=user).order_by(Collection.date_created.desc()).paginate(page=page, per_page=5)

    #data = Collection.query.paginate(page=page, per_page=5)
    return render_template('userdata.html', posts=data, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form  = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title="Reset Password", form=form)

mainapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username}}</h2>
      <p class="text-secondary">{{current_user.email}}</p>
    </div>
  </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}

                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
</div>
{% endblock content %}

mainapp/templates/datas.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.userdata', username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_created.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('datas.data', data_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('datas.dataall', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('datas.dataall', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

mainapp/templates/formview.html
{% extends "layout.html" %}
{% import 'formsinglerecordnavigation.html' as macros_single_nav %}
{% block content%}

<a class="btn btn-secondary btn-sm m-1" href="{{ url_for('forms.form_add', id=id) }}"> + Add new record</a>
          
    {% for f in form %}

                <article class="media content-section">
                    {{ macros_single_nav.render_single_row_nav(id, f[0]['id'], 'all', 'main_form') }}

                  <div class="media-body">
                       {% for field in f[1:] %}
                            <div class="form-group">
                                <label class="form-control-label">{{ field['label'] }}</label>
                                <input disabled type="text" class="form-control form-control-lg" value="{{ field['value'] }}">
                            </div>
                      {% endfor %}
                  </div>
                </article>
    {% endfor %}

{% endblock content%}

mainapp/templates/home.html
{% extends "layout.html" %}
{% block content %}
   <div class="content-section">
        <div class="media-body">
          <h2 class="account-heading">Collect data you want!</h2>
            <p>Collector Pro is an advanced application designed to simplify and enhance the process of creating custom forms, collecting data, and generating insightful reports</p>
            <p>Ideal for businesses, educational institutions, non-profits, and any organization that relies on efficient data collection and analysis, Collector Pro offers a comprehensive suite of tools to meet and exceed your needs.</p>
            <p>Collector Pro makes data collection straightforward and efficient.</p>
            <p> Once your forms are created, you can distribute them through various channels</p>

            <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('forms.form') }}">
See available forms</a>
            <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('forms.new_form') }}">Create your own form</a>
        </div>
   </div>

{% endblock content %}

mainapp/templates/layout.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
</head>
<body>
<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Collector</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle" style="justify-content: space-between">
            <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('forms.form') }}">Forms</a>
                <a class="nav-item nav-link" href="{{ url_for('forms.new_form') }}">New form</a>
                <a class="nav-item nav-link" href="javascript:void(0);" title="Display JSON" onclick="addJsonParam()">JSON</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}

                <a class="nav-item nav-link" title="Account" href="{{ url_for('users.account') }}"><?xml version="1.0" ?><svg class="feather feather-user" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></a>
                <a class="nav-item nav-link" title="Logout" href="{{ url_for('users.logout') }}"><?xml version="1.0" ?><svg class="feather feather-log-out" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" x2="9" y1="12" y2="12"/></svg></a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages%}
        {%for category, message in messages%}
        <div class="alert alert-{{ category}}">
            {{ message}}
        </div>
{% endfor%}
    {% endif%}
    {% endwith %}

    {% block content %}{% endblock %}
</div>

  <script>
        function addJsonParam() {
            const url = new URL(window.location.href);
            url.searchParams.set('type', 'json');
            window.location.href = url.href;
        }
    </script>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request')}}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

mainapp/templates/userdata.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.userdata', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_created.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('datas.data', data_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.userdata', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.userdata', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}